"""Initial migration

Revision ID: 0a546d706120
Revises: 
Create Date: 2025-07-04 16:20:48.666170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0a546d706120'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clients', 'licenses',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.create_index(op.f('ix_clients_id'), 'clients', ['id'], unique=False)
    op.create_unique_constraint(None, 'clients', ['db_name'])
    op.alter_column('documents', 'filename',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('documents', 'date',
               existing_type=mysql.DATETIME(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('documents', 'amount',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('documents', 'created_at',
               existing_type=mysql.DATETIME(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
    op.create_foreign_key(None, 'documents', 'clients', ['supplier_id'], ['id'])
    op.alter_column('parsed_oib', 'created_at',
               existing_type=mysql.DATETIME(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
    op.alter_column('parsed_oib', 'updated_at',
               existing_type=mysql.DATETIME(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
    op.create_unique_constraint('uq_oib', 'parsed_oib', ['oib'])
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_constraint('uq_oib', 'parsed_oib', type_='unique')
    op.alter_column('parsed_oib', 'updated_at',
               existing_type=sa.TIMESTAMP(),
               type_=mysql.DATETIME(),
               existing_nullable=True,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
    op.alter_column('parsed_oib', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=mysql.DATETIME(),
               existing_nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.alter_column('documents', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=mysql.DATETIME(),
               existing_nullable=True)
    op.alter_column('documents', 'amount',
               existing_type=sa.Integer(),
               type_=mysql.DECIMAL(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('documents', 'date',
               existing_type=sa.TIMESTAMP(),
               type_=mysql.DATETIME(),
               existing_nullable=True)
    op.alter_column('documents', 'filename',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.drop_constraint(None, 'clients', type_='unique')
    op.drop_index(op.f('ix_clients_id'), table_name='clients')
    op.alter_column('clients', 'licenses',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               existing_server_default=sa.text('1'))
    # ### end Alembic commands ###
